name: 1st-action-pipeline
on: 
  workflow_dispatch:   
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: greeting of the day
        run: echo "hello, ${{vars.FIRST_NAME}} ${{secrets.LAST_NAME}}"
      - name: list of command
        run: ls -a
   
