# File: .github/workflows/workflow.yml
on:
 push: 
jobs:
  example_matrix:
    strategy:
      os: [ubantu-latest, wandows-latest, macos-latest]
    name: matrix job
    runs-on: ${{ matrix.os }}
    steps:
      - run: ech "hello world"
      
   
