# File: .github/workflows/workflow.yml
on:
 push: 
jobs:
  my_First_job:
    name: First job
    runs-on: ubuntu-slim
    steps:
      - run: echo "My first job ran successful"
  my_second_job:
    name: Second job
    runs-on: ubuntu-slim
    steps:
      - run: echo "My second job ran successful"
